### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by vchatela** [markusressel/grocy-telegram-bot#26]
Hi,
Using this (part of) yaml config file :

```
grocy_telegram_bot:
  log_level: info
  locale: fr
  bot:
    shopping:
      remove_button_when_complete: True
  grocy:
    api_key: XXXX
    host: 192.168.1.54
    port: 15080
```

I have errors on the docker, url are not built : 

```
requests.exceptions.MissingSchema: Invalid URL 'chores': No schema supplied. Perhaps you meant http://shopping_list?
2020-04-12 12:38:27,330 - grocy_telegram_bot.monitoring.watcher - ERROR - Invalid URL 'objects/shopping_list': No schema supplied. Perhaps you meant http://objects/shopping_list?
```
